tech_corp_front_timeline:
    path: /timeline
    defaults: { _controller: TechCorpFrontBundle:Timeline:timeline }

tech_corp_front_user_timeline:
    path: /timeline/{userId}
    defaults: { _controller: TechCorpFrontBundle:Timeline:userTimeline }

tech_corp_front_friends_timeline:
    path: /friends_timeline/{userId}
    defaults: { _controller: TechCorpFrontBundle:Timeline:friendsTimeline }

testor_index:
    path: /testor
    defaults: { _controller: TechCorpFrontBundle:Testor:index }

testor_timeline:
    path: /testor_timeline
    defaults: { _controller: TechCorpFrontBundle:Testor:timelineTestor }

tech_corp_front_user_add_friend:
    path:  /user/add-friend/{friendId}
    defaults: { _controller: TechCorpFrontBundle:User:addFriend }
    requirements: { method: POST }

tech_corp_front_user_remove_friend:
    path:  /user/remove-friend/{friendId}
    defaults: { _controller: TechCorpFrontBundle:User:removeFriend }
    requirements: { method: POST }
