tech_corp_front_timeline:
    path: /timeline
    defaults: { _controller: TechCorpFrontBundle:Timeline:timeline }

tech_corp_front_user_timeline:
    path: /timeline/{userId}
    defaults: { _controller: TechCorpFrontBundle:Timeline:userTimeline }

tech_corp_front_friends_timeline:
    path: /friends_timeline/{userId}
    defaults: { _controller: TechCorpFrontBundle:Timeline:friendsTimeline }

