# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    providers:
        in_memory:
            memory:
                users:
                    john_user:
                        password: password
                        roles: 'ROLE_USER'
                    jack_admin:
                        password: password
                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        # Désactive l'authentification pour le Profiler et les ressources. Adaptez-le à votre guise.
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
            pattern: ^/secured/login$
            anonymous: ~

        secured_area:
            pattern: ^/secured
            form_login:
                provider: in_memory
                login_path: tech_corp_front_security_login
                check_path: tech_corp_front_security_login_check
            logout:
                path: tech_corp_front_security_logout
                target: tech_corp_front_security_login

        default:
            anonymous: ~
            # activate different ways to authenticate

    encoders:
        Symfony\Component\Security\Core\User\User:  plaintext

    #access_control:
    #    - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }