
app_front_homepage:
    defaults: { _controller: AppBundle:Default:index }
    path: /

app_ville:
    defaults: { _controller: AppBundle:Default:ville }
    path: /app_ville/{id}
    requirements:
        id: '\d+'

app_recherche:
    defaults: { _controller: AppBundle:Default:recherche }
    path: /searching
    methods: [post]

app_booking_homepage:
    defaults: { _controller: AppBundle:Booking:index }
    path: /booking_homepage

front_sheet_create:
    path: /sheet/created
    defaults: { _controller: AppBundle:Sheet:create }

front_sheet_list:
    path: /sheet/list
    defaults: [ _controller: AppBundle:Sheet:list ]

front_sheet_show:
    path: /sheet/{id}
    defaults: { _controller: AppBundle:Sheet:show }

front_sheet_ckeditor:
    path: /sheet_ckeditor
    defaults: { _controller: AppBundle:Sheet:editor }

front_sheet_ckeditor_list:
    path: /sheet_ckeditor_list
    defaults: { _controller: AppBundle:Sheet:listeditor }

front_sheet_ckeditor_modifier:
    path: /sheet_ckeditor_modify/{id}
    defaults: { _controller: AppBundle:Sheet:modifiereditor }
    requirements:
        id: '\d+'

appbundle_parameters:
    path: /app_bundle_parameters
    defaults: { _controller: AppBundle:Tools:requestParameters }

